import { db } from "./lib/client.js";

const verdicts: Record<string, string> = {

"bulk-peptide-supply": `Bulk Peptide Supply is one of the more transparent operations in this space: named ownership, a verified physical address, and seven products covered by Finnrick-verified independent testing. Average purity across those seven tests is 99.4%, with the lowest result a retatrutide batch at 96.8% — the only test below 98%. Two Finnrick labs are used across the catalog. No contact information is published, which is a gap given the otherwise clean identity record. Coverage is thin relative to catalog size — seven independently verified products across a range that runs wider than that. The core testing infrastructure is legitimate and the business accountability markers are in place. The contact information gap and thin coverage are the two areas that need to close before this vendor ranks higher.`,

"polaris-peptides": `Polaris runs COAs per product rather than a single page — each listing carries its own Chromate Analytics or Janoshik report. Eleven tested peptides average 99.4% purity, with no results below 98.36%. On top of that, Finnrick endotoxin records exist for multiple products, adding a second independent verification layer that most vendors at this score level don't have. Ownership is publicly disclosed. The COA archive requires a free account login to browse, which is a minor friction point but not unusual for a members-model vendor. Physical address is not on the public site. The testing documentation here — named labs, batch-specific COAs, independent endotoxin verification — is among the most comprehensive we review. The missing physical address is the one remaining accountability gap in an otherwise strong file.`,

"ez-peptides": `EZ Peptides posts third-party lab results confirmed through Finnrick across six tested products, and a physical US address is on file. Most purity results are clean — tirzepatide and GHK-Cu batches run 99.4–99.9%. The exception is a retatrutide batch (EZP-RET061209225-12) that came back at 93.2% — below the threshold where we start flagging product quality concerns. Notably, a second retatrutide batch tested the same day came back at 99.4%, which suggests a batch-specific problem rather than a systemic one, but neither result has been publicly addressed by the vendor. Ownership is not disclosed. The testing infrastructure is real and batch-traceable; the 93.2% outlier and the missing ownership disclosure are the two unresolved gaps before this vendor warrants a higher placement.`,

"peptidology": `Peptidology operates from Scottsdale, AZ (11111 North Scottsdale Rd, Suite 205), uses Vanguard Scientific Solutions — an ISO-17025 accredited independent lab — and maintains 171 batch-specific COA documents accessible through their COA library. Purity across reviewed records averages 99.6%, with the lowest confirmed result at 99.01%. Seven Finnrick-verified tests provide an additional independent verification layer. Contact information and a physical address are both public. The one transparency gap is ownership: the operator behind the business is not named. That aside, Peptidology's combination of an accredited testing lab, a documented archive with batch-level traceability, and an independent Finnrick record makes this one of the better-documented vendors we cover.`,

"orbitrex-peptides": `Orbitrex has a near-spotless purity record from seven Finnrick-verified tests: 99.8–99.9% across all results, with no test below 99.8%. Batch-specific COAs are issued, methodology is documented, and a physical address is on file. Contact information is absent, and ownership is not disclosed — two gaps in the accountability profile. The testing evidence is consistent enough that it crosses into a pattern rather than a lucky sample: seven independent tests with a 0.1% variance range is an unusually tight result set. The open items are the company identity gaps. Until contact information and ownership are published, buyers are transacting with a well-tested but partially anonymous operation.`,

"nextechlabs": `NextechLabs posts strong purity numbers — 99.69% average across seven Finnrick-verified products — but no browsable COA archive exists on the vendor's own site. The Finnrick records confirm the testing relationship, but independent document review isn't possible without that archive. No contact information is published. No ownership disclosure. A physical address is on file. The purity results (99.26–99.9% range across all batches) are clean, and the Finnrick footprint provides real independent verification. The COA archive gap limits how thoroughly buyers can validate before purchasing. A working public COA page is the threshold item before this vendor belongs in a higher tier.`,

"aavant-research": `Aavant Research posts some of the tightest purity numbers in this database — 99.87% average across seven Finnrick-verified tests, with no result below 99.7%. Two different Finnrick labs are used across the catalog, including multiple tirzepatide and retatrutide runs. Contact information is public. What's missing: no physical address, no ownership disclosure. The testing record alone would place this vendor higher if the business identity were more fully established. The company's principals are unknown. That's a real gap in accountability for a vendor operating in this space. The chemistry is well-documented; the operator is not.`,

"omegamino": `Four Finnrick-verified tests with an average purity of 99.8% and a floor of 99.63%. Third-party methodology is documented. The limitation is the sample: four tests is the minimum Finnrick footprint we'll accept as meaningful, and with no contact info, no physical address, and no ownership disclosure, the company operating behind those results is entirely anonymous. The purity data that exists is clean. The entity producing it has left no traceable identity. Adequate for buyers who prioritize test results over accountability; insufficient for buyers who consider both.`,

"astro-peptides": `Two CJC-1295 batches — lots CJC5-13596 tested May 2025 — came back at 88.99% and 85.65% purity. Both from the same batch on the same testing date, which suggests a single bad production run rather than an ongoing pattern. BPC-157, Semaglutide, and Ipamorelin results from the same testing date are clean (99.8–99.97%). The CJC-1295 failures haven't been publicly acknowledged by the vendor. No COA page is publicly accessible, no contact info is published, and no address or ownership is on file. Other products look fine; CJC-1295 from this vendor has a documented quality failure that hasn't been addressed. Do not buy CJC-1295 from Astro Peptides until the vendor accounts for those batch results.`,

"ruo-science": `RUO Science uses Freedom Diagnostics as their primary third-party testing lab — a US-based independent laboratory with a public searchable COA database. Confirmed lot LCARN500-02122026-J passes lookup at FreedomDiagnosticsTesting.com. Full-panel testing: HPLC-UV, mass spectrometry, endotoxin, sterility, and heavy metals. BPC-157 and tirzepatide batches reviewed show 99.12% and 99.74% purity respectively. Batch prefix patterns suggest multiple labs are used across the catalog (MB and VP prefixes indicate MZ Biolabs and Vanguard on some products). No business address or ownership disclosure is published. The lab is confirmed; the business operating behind it is not accountable at the level we'd want for a higher recommendation. Strong chemistry record that was previously undersold by an incomplete audit.`,

"simple-peptide": `Simple Peptide has seven Finnrick-verified tests, a working COA page, a physical US address, and both contact information and lab methodology disclosed — a more complete checklist than most vendors near this score. The scoring gap is purity data: no HPLC results have been extracted from their COA archive, so PQ scores zero. The score reflects the testing footprint rather than confirmed purity percentages. No ownership disclosure. This is a vendor with the right infrastructure in place; what's missing is confirmed numerical purity data. Worth monitoring as that data accumulates — the identity and accountability markers are better than average.`,

"paramount-peptides": `Paramount has eight Finnrick endotoxin tests — more independent testing records than most vendors above it in the rankings — and both a physical address and contact information are publicly listed. The problem is purity data: no HPLC results are in our database. Finnrick endotoxin records confirm a testing relationship but don't tell you product purity. Whether the absence of purity data reflects a scraping gap or a genuine lack of publicly published HPLC results, we can't confirm the chemistry independently. No ownership disclosure. The infrastructure signals are stronger than the score suggests; the chemistry documentation needs to be retrievable before we can rate this vendor higher.`,

"glacier-aminos": `COA documents are on file with batch numbers present, but the lab identity couldn't be confirmed from the page text or COA documents during our audit — the documents may be vendor-branded. Lab names appearing in our test records (Kovera Labs, Freedom Diagnostics) were identified through other means, not from the COA page itself. Three tests averaging 99.7% purity, with a floor at 99.13% (Thymosin Beta-4, January 2026). Contact information is public; no physical address or ownership disclosure. The sample size is thin and the lab attribution is not independently confirmed from vendor documentation. The existing results are clean, but three tests with unconfirmed lab attribution isn't sufficient for a strong recommendation.`,

"mile-high-compounds": `Mile High Compounds uses Chromate Analytics — a named third-party lab — across five tested products averaging 99.4% purity, with a floor at 99.09%. Batch-specific identifiers are present on all reviewed COAs. Ownership is disclosed and a physical address is on file. The jurisdiction flag: the operation uses a .is domain and runs outside US consumer protection frameworks. No contact information is published. The chemistry documentation is solid for this tier; the Iceland-based structure and missing contact info are the material risks. Buyers should factor in the limited legal recourse before ordering.`,

"ion-peptide": `Three independently named third-party labs — ILS Laboratories, Kovera Labs, and Freedom Diagnostics — across six tests averaging 99.7% purity, with a floor at 99.1% (5-Amino-1MQ, January 2026). Using multiple labs across a catalog is a genuine differentiator; it makes result manipulation harder and suggests the testing relationship isn't vendor-controlled. Physical address is on file. No contact information or ownership disclosure. The lab diversification here is a real signal, not a marketing claim. The accountability gaps — no contact info, no ownership — remain the ceiling on the recommendation.`,

"loti-labs": `Loti Labs is one of the more operationally transparent vendors in this space: ownership is publicly disclosed, contact info is listed, a physical address is on file, and Finnrick-verified testing exists. That context makes the CJC-1295 results harder to dismiss. Two separate CJC-1295 batches came back at 54.54% and 60.95% purity — not borderline, not near-miss. At those levels the product is predominantly something other than what it's labeled. Tirzepatide and retatrutide results are clean (99.04–99.91%). Loti has not publicly addressed the CJC-1295 failures. Until they do — with a new batch test, a statement, or a product removal — do not buy CJC-1295 from Loti Labs. Other products in the catalog have a clean record.`,

"paradigm-peptides": `Paradigm Peptides has Finnrick-verified testing across six products averaging 99.8% purity — the chemistry record is clean. The vendor is flagged in our database for unverified fraud reports, which zeroes out the Transparency sub-score and drives the overall score below 65 despite strong lab results. Ownership is not disclosed. No contact information, no physical address. The purity data is real; the company accountability profile raises concerns that test results alone don't resolve. We are not recommending purchases from this vendor until the fraud flag is resolved and basic identity transparency is established.`,

"verified-peptides": `Eight Finnrick-verified tests and an active COA page, but the operator is nearly anonymous — no contact info, no physical address, no ownership disclosure. No purity data is in our database from their COA archive, so we can't confirm the actual numbers; the score reflects the Finnrick testing footprint rather than confirmed purity percentages. The Finnrick coverage is meaningful for confirming a lab testing relationship, but buying from this vendor means transacting with a completely anonymous operation. Watchlist until identity transparency is established and purity data is independently confirmed.`,

"peptide-crafters": `Seven Finnrick-verified tests and an active COA page. Contact information is public. No purity data is in our database from their archive, so the score is driven by the Finnrick testing footprint rather than confirmed percentages. No physical address. No ownership disclosure. Notably, batch numbers are absent from the COA documents — a traceability gap that limits how specifically a buyer can verify a particular product lot. The testing infrastructure is real; the batch traceability and identity disclosure need to be built out before this vendor warrants a stronger rating.`,

"ascension-peptides": `Ascension uses Kovera Labs for full-panel COA testing: RP-HPLC purity, LC-MS identity confirmation, endotoxin screening (≤0.5 EU/mL), microbial sterility, and heavy metal panels (As, Cd, Pb, Hg). Batch-specific lot numbers are dated and traceable. Fifty-plus reviewed documents show purity averaging 99.6%, with a floor at 98.25%. COA access requires an age gate and account login, which limits casual verification but doesn't compromise the documentation quality behind it. No physical address or ownership disclosure is published — that is the remaining gap. Kovera Labs accreditation (A2LA/PJLA) has not been confirmed in public registries as of this review; if ISO 17025 accreditation is confirmed, the lab tier and score will be updated.`,

"peptide-partners": `Ownership is named and contact info is public — two accountability markers that put Peptide Partners ahead of most vendors at this score level. Finnrick-verified testing is confirmed, but no public COA archive is accessible for independent document review. No physical address is listed. No purity data is in our database. The company identity is sufficiently transparent for the score; what's missing is the ability to independently browse and verify the testing documentation. A browsable COA page with batch-specific records is the next step before we can confirm the chemistry side.`,

"felix-chemical-supply": `Felix uses two independently verified labs — Freedom Diagnostics and Chromate Analytical — and labels each batch entry by which lab ran the test. A subset of batches are dual-tested by both labs on the same lot, a verification standard higher than most T3 vendors. Per-product COA pages contain a full historical archive with batch-specific identifiers. Florida-based: 2800 N 6th St Unit 1, Saint Augustine, FL 32084. Pricing runs at the low end of the market. No ownership disclosure. The lab infrastructure is the strongest in this score tier: two named independent labs, explicit per-batch attribution, and a dual-testing protocol for selected lots. Ownership disclosure is the one remaining accountability gap.`,

"prime-peptides": `Prime Peptides is flagged for fraud reports and carries an active FDA warning — both of which zero out the Transparency sub-score regardless of testing record. The chemistry record is mixed: GHK-Cu and CJC-1295 results run 99.8–99.95%, but a BPC-157 batch (lot 5132025BP, July 2025) came back at 82.39% purity — a confirmed quality failure on one of the most commonly purchased products in this space. That failure, combined with the FDA warning and fraud flag, means we cannot recommend this vendor. The clean results elsewhere don't offset a documented failure and active regulatory action.`,

"nuscience-peptides": `Ten Finnrick-verified tests — one of the higher independent testing counts we track. No company identity disclosed: no contact info, no address, no ownership. Lab disclosure is absent from the vendor's own site. A COA page exists, but no purity data has been extracted from it. Free shipping on all orders. The Finnrick coverage is a real signal; everything about the operator behind it is a blank. The testing footprint alone isn't sufficient to recommend a vendor that has disclosed nothing about who runs it. Watchlist until identity transparency appears.`,

"skye-peptides": `Seventy-five Finnrick-verified tests across ten compounds — one of the highest testing footprints in our database. The results are not uniform: GLP-1 peptides (Semaglutide, Tirzepatide, Retatrutide) rate A Great. BPC-157 — one of the most commonly purchased peptides — rates E Bad, with a minimum Finnrick score of 2.6/10 across twelve tests. Ipamorelin rates C; CJC-1295 rates B. Zero company identity: no contact info, no address, no ownership disclosure, no lab named on-site. The testing footprint is large enough to be informative: BPC-157 from Skye Peptides has a documented quality problem across multiple independent tests. Do not buy BPC-157 from this vendor. GLP-1 results are clean, but the complete absence of any identity disclosure is a material concern at any score level.`,

"biotech-peptides": `Contact info, a physical address, and lab disclosure are all confirmed — a more complete identity profile than most vendors at this score level. COA page is active. No Finnrick testing exists, and no purity data is in our database. The audit confirmed the COA page does not identify the testing lab by name, so T1 (internal or unattributed testing) is the best we can verify. Good baseline legitimacy with a known gap: without confirmed independent lab identity, the COA documents can't be treated as externally verified quality evidence.`,

"crush-research": `Ownership is disclosed and contact info is public. COA page is active with batch numbers present, though the testing lab is not identified by name in reviewed documents — placing this in unattributed testing territory rather than confirmed third-party. No physical address. No purity data in our database. The company identity signals are solid; the testing documentation doesn't establish independent lab verification. Until a named third-party lab appears on the COA documents, the chemistry record is unconfirmed.`,

"swiss-chems": `Two CJC-1295 batches came back at 57.25% and 54.44% purity — both tested May 2025. At those levels, the product is predominantly not what it's labeled. Other tested peptides are clean: BPC-157 runs 99.71–99.95% across three batches, and Ipamorelin came back at 99.96%. Contact info is public. No physical address, no ownership disclosure. The Iceland .is domain limits US consumer protection recourse. Do not buy CJC-1295 from Swiss Chems. The rest of the catalog has clean test results, but the jurisdiction risk and missing identity transparency remain factors before a broader recommendation.`,

"sports-technology-labs": `Physical address and ownership both disclosed — more accountability than most vendors at this score level. MZ Biolabs COA confirmed via document inspection: HPLC-UV-MS, signed by analyst Ken Pendarvis ChE, with a real chromatogram and QR code for verification. No purity data extracted from their archive. No contact information published. Pricing runs at the high end of the market. The identity checks out and the lab has been confirmed as real. What's missing is a public purity record — without confirmed numbers, the pricing premium isn't justified by documented chemistry quality. Priced above peers with stronger publicly available test data.`,

"pure-rawz": `Seven Finnrick-verified tests suggest a real lab testing relationship exists. The COA page was blocked by Cloudflare during review — we couldn't confirm what's there or extract purity data. No contact info, no address, no ownership disclosure. One of the larger catalogs in this space; the complete operational anonymity is a meaningful concern given the scale of what they're selling. The Finnrick footprint is a floor on quality confidence; the anonymous structure and inaccessible documentation are the ceiling on how much confidence we can extend. Not recommended until COA access is restored and identity transparency is established.`,

"nexaph": `COAs are hosted on SwiftCS (nexaph.coa.swiftcs.ai) — a third-party COA verification platform. Unusual approach, but a legitimate one; the records are browsable without going through the vendor's own site. Ten Finnrick-verified tests, one of the higher counts in the database. No purity data extracted from the SwiftCS archive. No physical address, no ownership disclosure. No lab is named on the vendor's own site. Contact info is accessible. Above-market pricing across the catalog. The Finnrick coverage is the strongest evidence here; the missing identity infrastructure and premium pricing without confirmed purity data work against a stronger recommendation.`,

"true-research-labs": `COAs are issued by Horizon Analytical — a US-based lab whose reports include UPLC/MS methodology, full chromatograms with mass spec on page two, and a public verification portal at horizonanalytical.com. Lot TRL-9907743 confirmed, signed by Aleksey Yevtodiyenko PhD, analysis date 05/12/2026. A business address is confirmed (Sheridan, WY). COA page navigation is JavaScript-driven — documents aren't browsable without clicking through individual product buttons, which limits ease of independent verification. No ownership disclosure. No ISO 17025 accreditation confirmed for Horizon Analytical. The lab is real; the accessibility and verification tier lag behind what an accredited T4 lab would provide.`,

"certified-pep": `Certified Pep uses Vanguard Laboratory — ISO/IEC 17025:2017 accredited (A2LA #6377.01) — for purity, endotoxin, heavy metal, and bacterial testing. That is one of the most specific lab disclosures in this tier. The vendor's site is Cloudflare-protected, which prevented direct product and pricing verification during review. No physical address or ownership disclosure is public. Contact info is accessible. The testing infrastructure behind this vendor is demonstrably stronger than the score suggests — the score reflects a sparse data record rather than confirmed deficiencies. The lab disclosure alone puts this vendor ahead of most at a comparable overall score.`,

"amino-asylum": `Amino Asylum carries an active FDA warning and is flagged for fraud reports in our database. Both flags zero out the Transparency sub-score, regardless of testing record. Finnrick-verified testing exists — ownership and lab disclosure are confirmed — but regulatory action and documented fraud concerns override the testing record as the primary signal for buyers. Until the FDA matter is resolved and fraud reports are independently cleared, we do not recommend purchasing from this vendor.`,

"licensed-peptides": `Licensed Peptides uses Vanguard Laboratory (ISO 17025, A2LA accredited) for testing — confirmed via direct document inspection. That's a legitimate, accredited lab. The problem: COAs use cap color labels (Red Cap, Green Cap) as lot identifiers rather than actual batch numbers. Cap color is not a batch ID — it doesn't trace a specific production run. The chromatogram is partially obscured by the vendor's watermark. Products are sold exclusively in 10-vial packs, which inflates apparent pricing relative to per-vial vendors. Physical address and contact information are confirmed. Ownership is not disclosed. The lab is real and accredited; the batch traceability system undermines the reliability of that accreditation in practice. Score will rise when proper lot numbers replace cap-color identifiers.`,

"perfect-peptides": `COAs are tested by Chromate Analytical — confirmed via direct document inspection (Certificate #34141, verifiable at chromate.org/verify using access code PERFECT88HGR). Full panel: purity 99.294%, endotoxins 7.65 EU/vial, metals below 5ppb. Batch PP6896266 is specific and traceable. The problem: nothing beyond the lab is in place. No ownership disclosure, no business address, no community testing record, and no contact information. A T3-confirmed lab with a T1-grade operational transparency profile. The testing documentation is real; the vendor behind it is essentially anonymous. Worth monitoring as data accumulates, not a vendor we can recommend with the current disclosure level.`,

"core-peptides": `Third-party lab testing is confirmed, and contact info and a physical address are on file. COA page is active. No Finnrick testing. The batch traceability is the specific gap: COA documents lack batch-specific identifiers, meaning the same document applies to multiple production runs. That limits how precisely a buyer can trace what they received to a specific test. T2 testing (third-party, non-batch-specific) is real independent verification; it's just less granular than what a fully traceable COA provides. Ownership is not disclosed. Legitimate foundation that needs one more step on traceability before earning a stronger rating.`,

"cernum-biosciences": `Cernum Biosciences COAs are issued by their own internal "Lab Research Department" — not an independent third-party lab. Every product on the site carries the same batch number (201-139-35496), which is not a batch tracking system; it's a template. A 2026 press release placed on USA Today's paid wire service claims "independent third-party verification" and "batch-level traceability." Both claims are directly contradicted by the actual COA documents. Cernum is a newer operation with no community track record. The internal COA issuance, the repeated batch number, and the false third-party verification claim are three distinct transparency failures. We recommend looking elsewhere until genuine third-party lab results appear.`,

"lvlup-health": `No COA page and no lab testing documentation of any kind. Ownership is named. There is not enough evidence to evaluate product quality — we can verify who operates the business but not what the products contain. Not recommended until third-party testing documentation appears.`,

"limitless-biotech": `No COA page and no lab testing documentation. Contact information is public. Payments are PayPal-only, which provides less transaction protection than credit card purchases in cases of dispute. Not enough evidence to evaluate product quality. Not recommended without third-party testing.`,

"alpha-biomed-labs": `Institutional-access-only catalog — products are not publicly purchasable. Listed for completeness. No public documentation available to evaluate product quality or pricing.`,

"dynamic-peptide": `No COA, no lab testing, no contact info, no address, no ownership disclosure. One of the least-documented vendors in our database. We have no basis for evaluating product quality. Avoid.`,

"healthgevity": `No COA page and no lab testing documentation. Contact information is present but no physical address. Claims research-grade peptides with no independent verification to support the claim. Not recommended.`,

"penguin-peptides": `COA page exists. A physical address is on file. Testing is internal only — no named third-party lab has been identified in the documents. Without independent external testing, COA documents produced by or attributed to the vendor can't be treated as reliable quality evidence. Insufficient documentation for a buy recommendation.`,

"southern-peptides": `No documentation of any kind: no COA, no lab testing, no contact info, no address, no ownership. Lowest-documented vendor in our database. Avoid.`,

"maxx-research-supply": `The site is blocked by Cloudflare and is not indexed in public search. No products, prices, or documentation of any kind are publicly verifiable. The score of 5 reflects a data gap, not confirmed problems. We recommend waiting for more information before considering this vendor.`,

"apollo-peptide-sciences": `The apollopeptidesciences.com domain is not resolving. No products, no documentation, and no presence in third-party databases. This vendor appears to be offline. Listed for historical completeness only.`,

"pivot-labs": `The pivotlabs.com domain is parked with no active site. No products, no documentation, no operational presence. Listed for historical completeness only.`,

};

async function main() {
  let updated = 0;
  let errors = 0;
  for (const [slug, verdict] of Object.entries(verdicts)) {
    const { error } = await db.from("vendors").update({ verdict }).eq("slug", slug);
    if (error) {
      console.log(`ERROR ${slug}: ${error.message}`);
      errors++;
    } else {
      updated++;
      console.log(`OK ${slug}`);
    }
  }
  console.log(`\nDone: ${updated} updated, ${errors} errors`);
}

main().catch(console.error);
